/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JTrisGame.app;

import JTrisGame.app.controller.Controller;
import JTrisGame.app.model.Tris;
import java.util.Scanner;

public class App {

    static Tris tris;

    static Controller controller;

    static final Scanner scanner = new Scanner(System.in) ;

    public static void main(String[] args) {
        System.out.println("PARTITA TRIS");
        showMainMenu();
    }

    public static void showMainMenu(){
        int id1, id2;
        int num =0;

        System.out.println("P1 Inserisci id: ");
        id1 = scanner.nextInt();
        System.out.println("P2 Inserisci id: ");
        id2 = scanner.nextInt();
        tris = new Tris(id1, id2);
        controller = new Controller(tris);
        System.out.println("Partita creata - INIZIO");

        while (num<9) {
            num++;
            game();
            if (tris.getWinner() != null) {
                System.out.println("VINCE IL GIOCATORE: " + tris.getWinner());
                restart();
            }
        }

        if(num==9) {
            System.out.println("NESSUN VINCITORE");
            restart();
        }
    }


    private static void game(){
        int i, j;

        System.out.println("Turno giocatore: "+tris.getCurrentPlayer());
        System.out.println("Inserisci riga e colonna (0-2)");
        i = scanner.nextInt();
        j = scanner.nextInt();
        while (i>2 || j>2 || !tris.possibleMovement(i,j)){
            System.out.println("Errore : reinserire riga e colonna (0-2)");
            i = scanner.nextInt();
            j= scanner.nextInt();
        }
        controller.trisSetCasella(i,j);
        tris.printMatrix();
    }

    private static void restart(){
        int choice;
        System.out.println("Vuoi ricominciare la partita (1-si/2-no)");
        choice = scanner.nextInt();
        if(choice==1){
            controller.trisRestart();
            game();
        } else {
            System.out.println("FINE PARTITA");
            System.exit(0);
        }
    }
}
